export interface Reader {
  reader: string; // Hashed reader ID, generated by the browser and kept in a cookie
  likes: Map<string, number>; // Map of blog uuids and the number of likes
}

export interface BlogPost {
  uuid: string;
  tags: Array<string>;
  title: string;
  slug: string;
  summary: string;
  content: string;
  userAvatars: Array<string>;
  images: Array<string>;
  usernames: Array<string>;
  createdAt: string;
  readTime: string;
  likes: number;
  views: number;
  published: boolean;
}
